name: Unit Tests

on: [push, pull_request]

jobs:
  test:   
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest]
    
    name: Unit Tests - ${{matrix.os}}
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: pip install -e '.[testing]'
    - name: Run Pytest
      run: python -m pytest -s -v